### PR TITLE
Add support for Rails 6

### PR DESCRIPTION
**Pull request by afomera**
This PR adds support for Rails 6 to the gemspec.

What do you think about removing the upper dependency or moving it to be less than  `< 7`?

I imagine the asset pipeline will be around until then, as I haven't seen any plans announced yet to fully remove it from Rails just yet, and imagine they would only do so after deprecating it (maybe in Rails 6.1?)

### CODE REVIEW

**Comment by AnthonyClark** [comment]
@kylefox if you have the time it would be awesome to get this in

**Comment by afomera** [comment]
@kylefox If you'd like, I can help maintain the gem? ❤️

**Comment by afomera** [comment]
Hey guys, I've merged it into master. I'm moving over the next few weeks but will work on getting it so I can publish a new version to RubyGems, in the meantime, check it out from master and let us know if there are any more issues.

cc @AnthonyClark

**Comment by afomera** [comment]
Hi friends! I've just pushed 2.1.0 to RubyGems with support for Rails 6. Thanks for the patience!

**Comment by AnthonyClark** [comment]
Thank you @king601 !

**Pull request merged**
